### ISSUE TITLE
cx_Freeze: Python Error in main script

### ISSUE THREAD

**Issue by IIEleven11** [leigholiver/F2HabitBreaker#1]
Hi, So i have very very little experience with this, i am learning though. I'm trying to use this program and i'm getting this error: If there;s anything you can help me to do to fix this that'd be great. I have a major issue clicking this button and you seem to be the only one that has made a solution. Thank you!

![f2error](https://user-images.githubusercontent.com/55998857/65906327-33222580-e377-11e9-9a5f-0a6e14767e45.jpg)

**Comment by leigholiver** [comment]
It looks like the config file is missing, try [downloading this](https://raw.githubusercontent.com/leigholiver/F2HabitBreaker/master/F2HabitBreaker.csv ) and putting it into the same folder as the exe and it should work.

**Comment by IIEleven11** [comment]
Thanks For the fast response, so I click on the link you gave and it brings me to a blank page with what looks to be resolutions. 1920x1080,72,45,83,757
1680x1050,72,45,83,757,0,0,0,0.1
If youre talking about the excel document it is right next to the exe in the folder.  And it has those same values input

Sent from Mail for Windows 10

**Comment by leigholiver** [comment]
Are you running this from the source rather than from the exe?

**Comment by leigholiver** [comment]
Yes it is the excel document I am referring to - the error message you are seeing is because that file cannot be found. It must be a csv format file. If you havent customised that file at all its probably worth deleting the folder and downloading the zip file again.

**Comment by IIEleven11** [comment]
So I deleted and reinstalled it, I run it and I see this black box appear outside of SC2. So I go alt-tab into sc2 and its not there. Ill attack a screenshot. 

Sent from Mail for Windows 10

**Comment by IIEleven11** [comment]
I'm just double clicking the exe file in the folder.

**Comment by leigholiver** [comment]
Are you using Fullscreen mode in SC2? Im afraid the tool only works in windowed fullscreen

**Comment by IIEleven11** [comment]
Yep, that's what it was. I'm an idiot. But it works great. Going on hour
two. And uhm, I really want to take it off, ha. Any tips, I'm guessing you
used the blocker? Me and a friend looked at your code trying to figure out
what was going on. He said, "actually this is pretty nice, good
ettiquette." But yeah, this is great, thanks for making this! And thank you
for the fast replies and help. I appreciate.

**Comment by leigholiver** [comment]
Yeeeaaa its such a pain but definitely does the job! Thanks for the kind words. GLHF
